# Generated by Django 4.2.5 on 2023-09-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('endereco', models.TextField(blank=True)),
                ('convenio_medico', models.CharField(blank=True, max_length=100)),
                ('numero_carteira', models.CharField(blank=True, max_length=20)),
                ('numero_telefone', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('compareceu', models.BooleanField(default=False)),
                ('ordem_comparecimento', models.PositiveIntegerField(default=0)),
                ('convenio', models.CharField(blank=True, max_length=100)),
                ('num_carteira', models.CharField(blank=True, max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoclinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaoclinica.paciente')),
            ],
        ),
    ]
